// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: protocols/sbftslow/sbftslowpb/sbft.proto

package sbftslowpb

import (
	fmt "fmt"
	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/gogo/protobuf/proto"
	commandpb "github.com/ibalajiarun/go-consensus/pkg/command/commandpb"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type InstanceState_Status int32

const (
	InstanceState_None            InstanceState_Status = 0
	InstanceState_Preprepared     InstanceState_Status = 1
	InstanceState_SignShared      InstanceState_Status = 2
	InstanceState_Prepared        InstanceState_Status = 3
	InstanceState_CommitSigShared InstanceState_Status = 4
	InstanceState_Committed       InstanceState_Status = 5
	InstanceState_StateShared     InstanceState_Status = 6
	InstanceState_Executed        InstanceState_Status = 7
)

var InstanceState_Status_name = map[int32]string{
	0: "None",
	1: "Preprepared",
	2: "SignShared",
	3: "Prepared",
	4: "CommitSigShared",
	5: "Committed",
	6: "StateShared",
	7: "Executed",
}

var InstanceState_Status_value = map[string]int32{
	"None":            0,
	"Preprepared":     1,
	"SignShared":      2,
	"Prepared":        3,
	"CommitSigShared": 4,
	"Committed":       5,
	"StateShared":     6,
	"Executed":        7,
}

func (x InstanceState_Status) String() string {
	return proto.EnumName(InstanceState_Status_name, int32(x))
}

func (InstanceState_Status) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_2f29fa1c9e94b614, []int{1, 0}
}

type NormalMessage_Type int32

const (
	NormalMessage_None       NormalMessage_Type = 0
	NormalMessage_Preprepare NormalMessage_Type = 1
	NormalMessage_SignShare  NormalMessage_Type = 2
	NormalMessage_Prepare    NormalMessage_Type = 3
	NormalMessage_CommitSig  NormalMessage_Type = 4
	NormalMessage_CommitSlow NormalMessage_Type = 5
	NormalMessage_StateShare NormalMessage_Type = 6
	NormalMessage_ExecProof  NormalMessage_Type = 7
)

var NormalMessage_Type_name = map[int32]string{
	0: "None",
	1: "Preprepare",
	2: "SignShare",
	3: "Prepare",
	4: "CommitSig",
	5: "CommitSlow",
	6: "StateShare",
	7: "ExecProof",
}

var NormalMessage_Type_value = map[string]int32{
	"None":       0,
	"Preprepare": 1,
	"SignShare":  2,
	"Prepare":    3,
	"CommitSig":  4,
	"CommitSlow": 5,
	"StateShare": 6,
	"ExecProof":  7,
}

func (x NormalMessage_Type) String() string {
	return proto.EnumName(NormalMessage_Type_name, int32(x))
}

func (NormalMessage_Type) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_2f29fa1c9e94b614, []int{2, 0}
}

type SBFTMessage struct {
	// Types that are valid to be assigned to Type:
	//	*SBFTMessage_Normal
	//	*SBFTMessage_Result
	Type isSBFTMessage_Type `protobuf_oneof:"type"`
}

func (m *SBFTMessage) Reset()         { *m = SBFTMessage{} }
func (m *SBFTMessage) String() string { return proto.CompactTextString(m) }
func (*SBFTMessage) ProtoMessage()    {}
func (*SBFTMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_2f29fa1c9e94b614, []int{0}
}
func (m *SBFTMessage) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *SBFTMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_SBFTMessage.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *SBFTMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SBFTMessage.Merge(m, src)
}
func (m *SBFTMessage) XXX_Size() int {
	return m.Size()
}
func (m *SBFTMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_SBFTMessage.DiscardUnknown(m)
}

var xxx_messageInfo_SBFTMessage proto.InternalMessageInfo

type isSBFTMessage_Type interface {
	isSBFTMessage_Type()
	MarshalTo([]byte) (int, error)
	Size() int
}

type SBFTMessage_Normal struct {
	Normal *NormalMessage `protobuf:"bytes,1,opt,name=normal,proto3,oneof" json:"normal,omitempty"`
}
type SBFTMessage_Result struct {
	Result *ResultMessage `protobuf:"bytes,2,opt,name=result,proto3,oneof" json:"result,omitempty"`
}

func (*SBFTMessage_Normal) isSBFTMessage_Type() {}
func (*SBFTMessage_Result) isSBFTMessage_Type() {}

func (m *SBFTMessage) GetType() isSBFTMessage_Type {
	if m != nil {
		return m.Type
	}
	return nil
}

func (m *SBFTMessage) GetNormal() *NormalMessage {
	if x, ok := m.GetType().(*SBFTMessage_Normal); ok {
		return x.Normal
	}
	return nil
}

func (m *SBFTMessage) GetResult() *ResultMessage {
	if x, ok := m.GetType().(*SBFTMessage_Result); ok {
		return x.Result
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*SBFTMessage) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*SBFTMessage_Normal)(nil),
		(*SBFTMessage_Result)(nil),
	}
}

type InstanceState struct {
	View        View                 `protobuf:"varint,1,opt,name=view,proto3,casttype=View" json:"view,omitempty"`
	Index       Index                `protobuf:"varint,2,opt,name=index,proto3,casttype=Index" json:"index,omitempty"`
	Status      InstanceState_Status `protobuf:"varint,3,opt,name=status,proto3,enum=sbftslowpb.InstanceState_Status" json:"status,omitempty"`
	Command     *commandpb.Command   `protobuf:"bytes,4,opt,name=command,proto3" json:"command,omitempty"`
	CommandHash []byte               `protobuf:"bytes,5,opt,name=command_hash,json=commandHash,proto3" json:"command_hash,omitempty"`
}

func (m *InstanceState) Reset()         { *m = InstanceState{} }
func (m *InstanceState) String() string { return proto.CompactTextString(m) }
func (*InstanceState) ProtoMessage()    {}
func (*InstanceState) Descriptor() ([]byte, []int) {
	return fileDescriptor_2f29fa1c9e94b614, []int{1}
}
func (m *InstanceState) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *InstanceState) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_InstanceState.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *InstanceState) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InstanceState.Merge(m, src)
}
func (m *InstanceState) XXX_Size() int {
	return m.Size()
}
func (m *InstanceState) XXX_DiscardUnknown() {
	xxx_messageInfo_InstanceState.DiscardUnknown(m)
}

var xxx_messageInfo_InstanceState proto.InternalMessageInfo

func (m *InstanceState) GetView() View {
	if m != nil {
		return m.View
	}
	return 0
}

func (m *InstanceState) GetIndex() Index {
	if m != nil {
		return m.Index
	}
	return 0
}

func (m *InstanceState) GetStatus() InstanceState_Status {
	if m != nil {
		return m.Status
	}
	return InstanceState_None
}

func (m *InstanceState) GetCommand() *commandpb.Command {
	if m != nil {
		return m.Command
	}
	return nil
}

func (m *InstanceState) GetCommandHash() []byte {
	if m != nil {
		return m.CommandHash
	}
	return nil
}

type NormalMessage struct {
	View        View               `protobuf:"varint,1,opt,name=view,proto3,casttype=View" json:"view,omitempty"`
	Index       Index              `protobuf:"varint,2,opt,name=index,proto3,casttype=Index" json:"index,omitempty"`
	Type        NormalMessage_Type `protobuf:"varint,3,opt,name=type,proto3,enum=sbftslowpb.NormalMessage_Type" json:"type,omitempty"`
	Command     *commandpb.Command `protobuf:"bytes,4,opt,name=command,proto3" json:"command,omitempty"`
	CommandHash []byte             `protobuf:"bytes,5,opt,name=command_hash,json=commandHash,proto3" json:"command_hash,omitempty"`
}

func (m *NormalMessage) Reset()         { *m = NormalMessage{} }
func (m *NormalMessage) String() string { return proto.CompactTextString(m) }
func (*NormalMessage) ProtoMessage()    {}
func (*NormalMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_2f29fa1c9e94b614, []int{2}
}
func (m *NormalMessage) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *NormalMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_NormalMessage.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *NormalMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NormalMessage.Merge(m, src)
}
func (m *NormalMessage) XXX_Size() int {
	return m.Size()
}
func (m *NormalMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_NormalMessage.DiscardUnknown(m)
}

var xxx_messageInfo_NormalMessage proto.InternalMessageInfo

func (m *NormalMessage) GetView() View {
	if m != nil {
		return m.View
	}
	return 0
}

func (m *NormalMessage) GetIndex() Index {
	if m != nil {
		return m.Index
	}
	return 0
}

func (m *NormalMessage) GetType() NormalMessage_Type {
	if m != nil {
		return m.Type
	}
	return NormalMessage_None
}

func (m *NormalMessage) GetCommand() *commandpb.Command {
	if m != nil {
		return m.Command
	}
	return nil
}

func (m *NormalMessage) GetCommandHash() []byte {
	if m != nil {
		return m.CommandHash
	}
	return nil
}

type ResultMessage struct {
	Result []byte `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	Id     uint64 `protobuf:"varint,2,opt,name=id,proto3" json:"id,omitempty"`
}

func (m *ResultMessage) Reset()         { *m = ResultMessage{} }
func (m *ResultMessage) String() string { return proto.CompactTextString(m) }
func (*ResultMessage) ProtoMessage()    {}
func (*ResultMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_2f29fa1c9e94b614, []int{3}
}
func (m *ResultMessage) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *ResultMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_ResultMessage.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *ResultMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResultMessage.Merge(m, src)
}
func (m *ResultMessage) XXX_Size() int {
	return m.Size()
}
func (m *ResultMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_ResultMessage.DiscardUnknown(m)
}

var xxx_messageInfo_ResultMessage proto.InternalMessageInfo

func (m *ResultMessage) GetResult() []byte {
	if m != nil {
		return m.Result
	}
	return nil
}

func (m *ResultMessage) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func init() {
	proto.RegisterEnum("sbftslowpb.InstanceState_Status", InstanceState_Status_name, InstanceState_Status_value)
	proto.RegisterEnum("sbftslowpb.NormalMessage_Type", NormalMessage_Type_name, NormalMessage_Type_value)
	proto.RegisterType((*SBFTMessage)(nil), "sbftslowpb.SBFTMessage")
	proto.RegisterType((*InstanceState)(nil), "sbftslowpb.InstanceState")
	proto.RegisterType((*NormalMessage)(nil), "sbftslowpb.NormalMessage")
	proto.RegisterType((*ResultMessage)(nil), "sbftslowpb.ResultMessage")
}

func init() {
	proto.RegisterFile("protocols/sbftslow/sbftslowpb/sbft.proto", fileDescriptor_2f29fa1c9e94b614)
}

var fileDescriptor_2f29fa1c9e94b614 = []byte{
	// 561 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x94, 0xbf, 0x6f, 0xd3, 0x40,
	0x14, 0xc7, 0x63, 0xd7, 0x71, 0xda, 0x97, 0x26, 0xb5, 0x0e, 0x84, 0x42, 0x85, 0xdc, 0x10, 0x96,
	0x0c, 0x60, 0x4b, 0xed, 0x00, 0x2b, 0x41, 0xa0, 0x76, 0xa0, 0x8a, 0xec, 0x8a, 0x01, 0x06, 0x74,
	0x8e, 0xaf, 0xce, 0x81, 0xe3, 0xb3, 0x7c, 0x67, 0xd2, 0xb2, 0xb0, 0xf0, 0x07, 0xf0, 0x67, 0xb1,
	0xd1, 0x91, 0xa9, 0xaa, 0x92, 0xff, 0xa2, 0x13, 0xba, 0xf3, 0xe5, 0x97, 0x10, 0x2c, 0x30, 0xe5,
	0xdd, 0xf7, 0x7d, 0xdf, 0xbd, 0xbb, 0xcf, 0xbb, 0x18, 0xfa, 0x79, 0xc1, 0x04, 0x1b, 0xb1, 0x94,
	0xfb, 0x3c, 0x3a, 0x17, 0x3c, 0x65, 0xd3, 0x65, 0x90, 0x47, 0x2a, 0xf4, 0x94, 0x05, 0xc1, 0x4a,
	0xde, 0xbf, 0x9b, 0xb0, 0x84, 0x29, 0xd9, 0x97, 0x51, 0xe5, 0xd8, 0x7f, 0x94, 0x7f, 0x4c, 0xfc,
	0x11, 0x9b, 0x4c, 0x70, 0x16, 0x2f, 0x7e, 0xf3, 0x68, 0x11, 0x55, 0xa6, 0xde, 0x17, 0x68, 0x86,
	0x83, 0x57, 0x67, 0xaf, 0x09, 0xe7, 0x38, 0x21, 0xe8, 0x08, 0xec, 0x8c, 0x15, 0x13, 0x9c, 0x76,
	0x8c, 0xae, 0xd1, 0x6f, 0x1e, 0xde, 0xf7, 0x56, 0x6d, 0xbc, 0x53, 0x95, 0xd1, 0xd6, 0xe3, 0x5a,
	0xa0, 0xad, 0xb2, 0xa8, 0x20, 0xbc, 0x4c, 0x45, 0xc7, 0xfc, 0xbd, 0x28, 0x50, 0x99, 0xb5, 0xa2,
	0xca, 0x3a, 0xb0, 0xc1, 0x12, 0x97, 0x39, 0xe9, 0xdd, 0x98, 0xd0, 0x3a, 0xc9, 0xb8, 0xc0, 0xd9,
	0x88, 0x84, 0x02, 0x0b, 0x82, 0x1e, 0x80, 0xf5, 0x89, 0x92, 0xa9, 0x3a, 0x81, 0x35, 0xd8, 0xbe,
	0xbd, 0x3e, 0xb0, 0xde, 0x50, 0x32, 0x0d, 0x94, 0x8a, 0x0e, 0xa0, 0x4e, 0xb3, 0x98, 0x5c, 0xa8,
	0x5e, 0xd6, 0x60, 0xe7, 0xf6, 0xfa, 0xa0, 0x7e, 0x22, 0x85, 0xa0, 0xd2, 0xd1, 0x33, 0xb0, 0xb9,
	0xc0, 0xa2, 0xe4, 0x9d, 0xad, 0xae, 0xd1, 0x6f, 0x1f, 0x76, 0xd7, 0x4f, 0xb3, 0xd1, 0xc9, 0x0b,
	0x95, 0x2f, 0xd0, 0x7e, 0xf4, 0x18, 0x1a, 0x1a, 0x4e, 0xc7, 0x52, 0x17, 0x41, 0xde, 0x12, 0x9b,
	0xf7, 0xa2, 0x8a, 0x82, 0x85, 0x05, 0x3d, 0x84, 0x5d, 0x1d, 0xbe, 0x1f, 0x63, 0x3e, 0xee, 0xd4,
	0xbb, 0x46, 0x7f, 0x37, 0x68, 0x6a, 0xed, 0x18, 0xf3, 0x71, 0xef, 0xab, 0x01, 0x76, 0xd5, 0x03,
	0x6d, 0x83, 0x75, 0xca, 0x32, 0xe2, 0xd4, 0xd0, 0x1e, 0x34, 0x87, 0x05, 0xc9, 0x0b, 0x92, 0xe3,
	0x82, 0xc4, 0x8e, 0x81, 0xda, 0x00, 0x21, 0x4d, 0xb2, 0x70, 0xac, 0xd6, 0x26, 0xda, 0x85, 0xed,
	0xe1, 0x22, 0xbb, 0x85, 0xee, 0xc0, 0x9e, 0x6c, 0x4d, 0x45, 0x48, 0x13, 0x6d, 0xb1, 0x50, 0x0b,
	0x76, 0x2a, 0x51, 0x90, 0xd8, 0xa9, 0xcb, 0x2d, 0xd5, 0x85, 0x74, 0xde, 0x96, 0x5b, 0xbc, 0xbc,
	0x20, 0xa3, 0x52, 0xa6, 0x1b, 0xbd, 0x1f, 0x26, 0xb4, 0x36, 0x66, 0xf7, 0xaf, 0x88, 0x0f, 0xab,
	0xd9, 0x69, 0xc0, 0xee, 0x1f, 0xdf, 0x88, 0x77, 0x76, 0x99, 0x93, 0x40, 0x79, 0xff, 0x3f, 0xdc,
	0xcf, 0x60, 0xc9, 0xed, 0xd7, 0xc8, 0xb6, 0x01, 0x56, 0x64, 0x1d, 0x43, 0x52, 0x5a, 0x82, 0x75,
	0x4c, 0xd4, 0x84, 0x86, 0xe6, 0xea, 0x6c, 0xad, 0x08, 0x86, 0x34, 0x71, 0x2c, 0x59, 0xaa, 0x97,
	0x29, 0x9b, 0x3a, 0x75, 0x35, 0x93, 0x25, 0x51, 0xc7, 0x96, 0x76, 0x09, 0x74, 0x58, 0x30, 0x76,
	0xee, 0x34, 0x7a, 0x4f, 0xa1, 0xb5, 0xf1, 0xae, 0xd1, 0xbd, 0xe5, 0x5f, 0xc0, 0x50, 0x27, 0xd5,
	0x2b, 0xd4, 0x06, 0x93, 0xc6, 0x15, 0xc7, 0xc0, 0xa4, 0xf1, 0xe0, 0xdd, 0xf7, 0x99, 0x6b, 0x5c,
	0xcd, 0x5c, 0xe3, 0x66, 0xe6, 0x1a, 0xdf, 0xe6, 0x6e, 0xed, 0x6a, 0xee, 0xd6, 0x7e, 0xce, 0xdd,
	0xda, 0xdb, 0xe7, 0x09, 0x15, 0xe3, 0x32, 0x92, 0x50, 0x7c, 0x1a, 0xe1, 0x14, 0x7f, 0xa0, 0xb8,
	0x28, 0x33, 0x3f, 0x61, 0x4f, 0x46, 0x2c, 0xe3, 0x24, 0xe3, 0x25, 0xf7, 0xff, 0xfa, 0x75, 0x88,
	0x6c, 0x95, 0x3e, 0xfa, 0x15, 0x00, 0x00, 0xff, 0xff, 0xca, 0x30, 0x0d, 0xd4, 0x45, 0x04, 0x00,
	0x00,
}

func (m *SBFTMessage) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *SBFTMessage) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *SBFTMessage) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Type != nil {
		{
			size := m.Type.Size()
			i -= size
			if _, err := m.Type.MarshalTo(dAtA[i:]); err != nil {
				return 0, err
			}
		}
	}
	return len(dAtA) - i, nil
}

func (m *SBFTMessage_Normal) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *SBFTMessage_Normal) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	if m.Normal != nil {
		{
			size, err := m.Normal.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintSbft(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}
func (m *SBFTMessage_Result) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *SBFTMessage_Result) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	if m.Result != nil {
		{
			size, err := m.Result.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintSbft(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x12
	}
	return len(dAtA) - i, nil
}
func (m *InstanceState) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *InstanceState) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *InstanceState) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.CommandHash) > 0 {
		i -= len(m.CommandHash)
		copy(dAtA[i:], m.CommandHash)
		i = encodeVarintSbft(dAtA, i, uint64(len(m.CommandHash)))
		i--
		dAtA[i] = 0x2a
	}
	if m.Command != nil {
		{
			size, err := m.Command.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintSbft(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x22
	}
	if m.Status != 0 {
		i = encodeVarintSbft(dAtA, i, uint64(m.Status))
		i--
		dAtA[i] = 0x18
	}
	if m.Index != 0 {
		i = encodeVarintSbft(dAtA, i, uint64(m.Index))
		i--
		dAtA[i] = 0x10
	}
	if m.View != 0 {
		i = encodeVarintSbft(dAtA, i, uint64(m.View))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *NormalMessage) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *NormalMessage) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *NormalMessage) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.CommandHash) > 0 {
		i -= len(m.CommandHash)
		copy(dAtA[i:], m.CommandHash)
		i = encodeVarintSbft(dAtA, i, uint64(len(m.CommandHash)))
		i--
		dAtA[i] = 0x2a
	}
	if m.Command != nil {
		{
			size, err := m.Command.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintSbft(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x22
	}
	if m.Type != 0 {
		i = encodeVarintSbft(dAtA, i, uint64(m.Type))
		i--
		dAtA[i] = 0x18
	}
	if m.Index != 0 {
		i = encodeVarintSbft(dAtA, i, uint64(m.Index))
		i--
		dAtA[i] = 0x10
	}
	if m.View != 0 {
		i = encodeVarintSbft(dAtA, i, uint64(m.View))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *ResultMessage) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *ResultMessage) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *ResultMessage) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Id != 0 {
		i = encodeVarintSbft(dAtA, i, uint64(m.Id))
		i--
		dAtA[i] = 0x10
	}
	if len(m.Result) > 0 {
		i -= len(m.Result)
		copy(dAtA[i:], m.Result)
		i = encodeVarintSbft(dAtA, i, uint64(len(m.Result)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintSbft(dAtA []byte, offset int, v uint64) int {
	offset -= sovSbft(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *SBFTMessage) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Type != nil {
		n += m.Type.Size()
	}
	return n
}

func (m *SBFTMessage_Normal) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Normal != nil {
		l = m.Normal.Size()
		n += 1 + l + sovSbft(uint64(l))
	}
	return n
}
func (m *SBFTMessage_Result) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Result != nil {
		l = m.Result.Size()
		n += 1 + l + sovSbft(uint64(l))
	}
	return n
}
func (m *InstanceState) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.View != 0 {
		n += 1 + sovSbft(uint64(m.View))
	}
	if m.Index != 0 {
		n += 1 + sovSbft(uint64(m.Index))
	}
	if m.Status != 0 {
		n += 1 + sovSbft(uint64(m.Status))
	}
	if m.Command != nil {
		l = m.Command.Size()
		n += 1 + l + sovSbft(uint64(l))
	}
	l = len(m.CommandHash)
	if l > 0 {
		n += 1 + l + sovSbft(uint64(l))
	}
	return n
}

func (m *NormalMessage) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.View != 0 {
		n += 1 + sovSbft(uint64(m.View))
	}
	if m.Index != 0 {
		n += 1 + sovSbft(uint64(m.Index))
	}
	if m.Type != 0 {
		n += 1 + sovSbft(uint64(m.Type))
	}
	if m.Command != nil {
		l = m.Command.Size()
		n += 1 + l + sovSbft(uint64(l))
	}
	l = len(m.CommandHash)
	if l > 0 {
		n += 1 + l + sovSbft(uint64(l))
	}
	return n
}

func (m *ResultMessage) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Result)
	if l > 0 {
		n += 1 + l + sovSbft(uint64(l))
	}
	if m.Id != 0 {
		n += 1 + sovSbft(uint64(m.Id))
	}
	return n
}

func sovSbft(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozSbft(x uint64) (n int) {
	return sovSbft(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *SBFTMessage) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowSbft
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: SBFTMessage: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: SBFTMessage: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Normal", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSbft
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthSbft
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthSbft
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			v := &NormalMessage{}
			if err := v.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			m.Type = &SBFTMessage_Normal{v}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Result", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSbft
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthSbft
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthSbft
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			v := &ResultMessage{}
			if err := v.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			m.Type = &SBFTMessage_Result{v}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipSbft(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthSbft
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthSbft
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *InstanceState) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowSbft
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: InstanceState: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: InstanceState: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field View", wireType)
			}
			m.View = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSbft
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.View |= View(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Index", wireType)
			}
			m.Index = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSbft
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Index |= Index(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Status", wireType)
			}
			m.Status = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSbft
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Status |= InstanceState_Status(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Command", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSbft
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthSbft
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthSbft
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Command == nil {
				m.Command = &commandpb.Command{}
			}
			if err := m.Command.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field CommandHash", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSbft
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthSbft
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthSbft
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.CommandHash = append(m.CommandHash[:0], dAtA[iNdEx:postIndex]...)
			if m.CommandHash == nil {
				m.CommandHash = []byte{}
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipSbft(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthSbft
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthSbft
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *NormalMessage) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowSbft
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: NormalMessage: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: NormalMessage: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field View", wireType)
			}
			m.View = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSbft
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.View |= View(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Index", wireType)
			}
			m.Index = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSbft
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Index |= Index(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Type", wireType)
			}
			m.Type = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSbft
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Type |= NormalMessage_Type(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Command", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSbft
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthSbft
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthSbft
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Command == nil {
				m.Command = &commandpb.Command{}
			}
			if err := m.Command.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field CommandHash", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSbft
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthSbft
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthSbft
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.CommandHash = append(m.CommandHash[:0], dAtA[iNdEx:postIndex]...)
			if m.CommandHash == nil {
				m.CommandHash = []byte{}
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipSbft(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthSbft
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthSbft
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *ResultMessage) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowSbft
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: ResultMessage: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: ResultMessage: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Result", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSbft
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthSbft
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthSbft
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Result = append(m.Result[:0], dAtA[iNdEx:postIndex]...)
			if m.Result == nil {
				m.Result = []byte{}
			}
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Id", wireType)
			}
			m.Id = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSbft
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Id |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipSbft(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthSbft
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthSbft
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipSbft(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowSbft
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowSbft
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowSbft
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthSbft
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupSbft
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthSbft
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthSbft        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowSbft          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupSbft = fmt.Errorf("proto: unexpected end of group")
)
