// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: protocols/hybsterx/hybsterxpb/hybsterx.proto

package hybsterxpb

import (
	fmt "fmt"
	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/gogo/protobuf/proto"
	github_com_ibalajiarun_go_consensus_peer_peerpb "github.com/ibalajiarun/go-consensus/peer/peerpb"
	commandpb "github.com/ibalajiarun/go-consensus/pkg/command/commandpb"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type InstanceState_Status int32

const (
	InstanceState_None      InstanceState_Status = 0
	InstanceState_Prepared  InstanceState_Status = 1
	InstanceState_Committed InstanceState_Status = 2
	InstanceState_Executed  InstanceState_Status = 3
)

var InstanceState_Status_name = map[int32]string{
	0: "None",
	1: "Prepared",
	2: "Committed",
	3: "Executed",
}

var InstanceState_Status_value = map[string]int32{
	"None":      0,
	"Prepared":  1,
	"Committed": 2,
	"Executed":  3,
}

func (x InstanceState_Status) String() string {
	return proto.EnumName(InstanceState_Status_name, int32(x))
}

func (InstanceState_Status) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_2d276307e2212edc, []int{2, 0}
}

type NormalMessage_Type int32

const (
	NormalMessage_None    NormalMessage_Type = 0
	NormalMessage_Prepare NormalMessage_Type = 1
	NormalMessage_Commit  NormalMessage_Type = 3
)

var NormalMessage_Type_name = map[int32]string{
	0: "None",
	1: "Prepare",
	3: "Commit",
}

var NormalMessage_Type_value = map[string]int32{
	"None":    0,
	"Prepare": 1,
	"Commit":  3,
}

func (x NormalMessage_Type) String() string {
	return proto.EnumName(NormalMessage_Type_name, int32(x))
}

func (NormalMessage_Type) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_2d276307e2212edc, []int{3, 0}
}

type OInstanceState_Status int32

const (
	OInstanceState_None      OInstanceState_Status = 0
	OInstanceState_Prepared  OInstanceState_Status = 1
	OInstanceState_Committed OInstanceState_Status = 2
	OInstanceState_Executed  OInstanceState_Status = 3
)

var OInstanceState_Status_name = map[int32]string{
	0: "None",
	1: "Prepared",
	2: "Committed",
	3: "Executed",
}

var OInstanceState_Status_value = map[string]int32{
	"None":      0,
	"Prepared":  1,
	"Committed": 2,
	"Executed":  3,
}

func (x OInstanceState_Status) String() string {
	return proto.EnumName(OInstanceState_Status_name, int32(x))
}

func (OInstanceState_Status) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_2d276307e2212edc, []int{4, 0}
}

type ONormalMessage_Type int32

const (
	ONormalMessage_None     ONormalMessage_Type = 0
	ONormalMessage_OPrepare ONormalMessage_Type = 1
	ONormalMessage_OCommit  ONormalMessage_Type = 2
)

var ONormalMessage_Type_name = map[int32]string{
	0: "None",
	1: "OPrepare",
	2: "OCommit",
}

var ONormalMessage_Type_value = map[string]int32{
	"None":     0,
	"OPrepare": 1,
	"OCommit":  2,
}

func (x ONormalMessage_Type) String() string {
	return proto.EnumName(ONormalMessage_Type_name, int32(x))
}

func (ONormalMessage_Type) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_2d276307e2212edc, []int{5, 0}
}

type HybsterxMessage struct {
	// Types that are valid to be assigned to Type:
	//	*HybsterxMessage_Normal
	//	*HybsterxMessage_ONormal
	Type isHybsterxMessage_Type `protobuf_oneof:"type"`
}

func (m *HybsterxMessage) Reset()         { *m = HybsterxMessage{} }
func (m *HybsterxMessage) String() string { return proto.CompactTextString(m) }
func (*HybsterxMessage) ProtoMessage()    {}
func (*HybsterxMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_2d276307e2212edc, []int{0}
}
func (m *HybsterxMessage) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *HybsterxMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_HybsterxMessage.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *HybsterxMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HybsterxMessage.Merge(m, src)
}
func (m *HybsterxMessage) XXX_Size() int {
	return m.Size()
}
func (m *HybsterxMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_HybsterxMessage.DiscardUnknown(m)
}

var xxx_messageInfo_HybsterxMessage proto.InternalMessageInfo

type isHybsterxMessage_Type interface {
	isHybsterxMessage_Type()
	MarshalTo([]byte) (int, error)
	Size() int
}

type HybsterxMessage_Normal struct {
	Normal *NormalMessage `protobuf:"bytes,1,opt,name=normal,proto3,oneof" json:"normal,omitempty"`
}
type HybsterxMessage_ONormal struct {
	ONormal *ONormalMessage `protobuf:"bytes,2,opt,name=oNormal,proto3,oneof" json:"oNormal,omitempty"`
}

func (*HybsterxMessage_Normal) isHybsterxMessage_Type()  {}
func (*HybsterxMessage_ONormal) isHybsterxMessage_Type() {}

func (m *HybsterxMessage) GetType() isHybsterxMessage_Type {
	if m != nil {
		return m.Type
	}
	return nil
}

func (m *HybsterxMessage) GetNormal() *NormalMessage {
	if x, ok := m.GetType().(*HybsterxMessage_Normal); ok {
		return x.Normal
	}
	return nil
}

func (m *HybsterxMessage) GetONormal() *ONormalMessage {
	if x, ok := m.GetType().(*HybsterxMessage_ONormal); ok {
		return x.ONormal
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*HybsterxMessage) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*HybsterxMessage_Normal)(nil),
		(*HybsterxMessage_ONormal)(nil),
	}
}

type InstanceID struct {
	PeerID github_com_ibalajiarun_go_consensus_peer_peerpb.PeerID `protobuf:"varint,1,opt,name=peer_id,json=peerId,proto3,casttype=github.com/ibalajiarun/go-consensus/peer/peerpb.PeerID" json:"peer_id,omitempty"`
	Index  Index                                                  `protobuf:"varint,2,opt,name=index,proto3,casttype=Index" json:"index,omitempty"`
}

func (m *InstanceID) Reset()         { *m = InstanceID{} }
func (m *InstanceID) String() string { return proto.CompactTextString(m) }
func (*InstanceID) ProtoMessage()    {}
func (*InstanceID) Descriptor() ([]byte, []int) {
	return fileDescriptor_2d276307e2212edc, []int{1}
}
func (m *InstanceID) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *InstanceID) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_InstanceID.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *InstanceID) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InstanceID.Merge(m, src)
}
func (m *InstanceID) XXX_Size() int {
	return m.Size()
}
func (m *InstanceID) XXX_DiscardUnknown() {
	xxx_messageInfo_InstanceID.DiscardUnknown(m)
}

var xxx_messageInfo_InstanceID proto.InternalMessageInfo

func (m *InstanceID) GetPeerID() github_com_ibalajiarun_go_consensus_peer_peerpb.PeerID {
	if m != nil {
		return m.PeerID
	}
	return 0
}

func (m *InstanceID) GetIndex() Index {
	if m != nil {
		return m.Index
	}
	return 0
}

type InstanceState struct {
	View        View                 `protobuf:"varint,1,opt,name=view,proto3,casttype=View" json:"view,omitempty"`
	InstanceID  InstanceID           `protobuf:"bytes,2,opt,name=instance_id,json=instanceId,proto3" json:"instance_id"`
	Status      InstanceState_Status `protobuf:"varint,3,opt,name=status,proto3,enum=hybsterxpb.InstanceState_Status" json:"status,omitempty"`
	Command     *commandpb.Command   `protobuf:"bytes,4,opt,name=command,proto3" json:"command,omitempty"`
	CommandHash []byte               `protobuf:"bytes,5,opt,name=command_hash,json=commandHash,proto3" json:"command_hash,omitempty"`
}

func (m *InstanceState) Reset()         { *m = InstanceState{} }
func (m *InstanceState) String() string { return proto.CompactTextString(m) }
func (*InstanceState) ProtoMessage()    {}
func (*InstanceState) Descriptor() ([]byte, []int) {
	return fileDescriptor_2d276307e2212edc, []int{2}
}
func (m *InstanceState) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *InstanceState) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_InstanceState.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *InstanceState) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InstanceState.Merge(m, src)
}
func (m *InstanceState) XXX_Size() int {
	return m.Size()
}
func (m *InstanceState) XXX_DiscardUnknown() {
	xxx_messageInfo_InstanceState.DiscardUnknown(m)
}

var xxx_messageInfo_InstanceState proto.InternalMessageInfo

func (m *InstanceState) GetView() View {
	if m != nil {
		return m.View
	}
	return 0
}

func (m *InstanceState) GetInstanceID() InstanceID {
	if m != nil {
		return m.InstanceID
	}
	return InstanceID{}
}

func (m *InstanceState) GetStatus() InstanceState_Status {
	if m != nil {
		return m.Status
	}
	return InstanceState_None
}

func (m *InstanceState) GetCommand() *commandpb.Command {
	if m != nil {
		return m.Command
	}
	return nil
}

func (m *InstanceState) GetCommandHash() []byte {
	if m != nil {
		return m.CommandHash
	}
	return nil
}

type NormalMessage struct {
	View        View               `protobuf:"varint,1,opt,name=view,proto3,casttype=View" json:"view,omitempty"`
	InstanceID  InstanceID         `protobuf:"bytes,2,opt,name=instance_id,json=instanceId,proto3" json:"instance_id"`
	Type        NormalMessage_Type `protobuf:"varint,3,opt,name=type,proto3,enum=hybsterxpb.NormalMessage_Type" json:"type,omitempty"`
	Command     *commandpb.Command `protobuf:"bytes,4,opt,name=command,proto3" json:"command,omitempty"`
	CommandHash []byte             `protobuf:"bytes,5,opt,name=command_hash,json=commandHash,proto3" json:"command_hash,omitempty"`
}

func (m *NormalMessage) Reset()         { *m = NormalMessage{} }
func (m *NormalMessage) String() string { return proto.CompactTextString(m) }
func (*NormalMessage) ProtoMessage()    {}
func (*NormalMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_2d276307e2212edc, []int{3}
}
func (m *NormalMessage) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *NormalMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_NormalMessage.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *NormalMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NormalMessage.Merge(m, src)
}
func (m *NormalMessage) XXX_Size() int {
	return m.Size()
}
func (m *NormalMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_NormalMessage.DiscardUnknown(m)
}

var xxx_messageInfo_NormalMessage proto.InternalMessageInfo

func (m *NormalMessage) GetView() View {
	if m != nil {
		return m.View
	}
	return 0
}

func (m *NormalMessage) GetInstanceID() InstanceID {
	if m != nil {
		return m.InstanceID
	}
	return InstanceID{}
}

func (m *NormalMessage) GetType() NormalMessage_Type {
	if m != nil {
		return m.Type
	}
	return NormalMessage_None
}

func (m *NormalMessage) GetCommand() *commandpb.Command {
	if m != nil {
		return m.Command
	}
	return nil
}

func (m *NormalMessage) GetCommandHash() []byte {
	if m != nil {
		return m.CommandHash
	}
	return nil
}

type OInstanceState struct {
	View        View                  `protobuf:"varint,1,opt,name=view,proto3,casttype=View" json:"view,omitempty"`
	Index       Index                 `protobuf:"varint,2,opt,name=index,proto3,casttype=Index" json:"index,omitempty"`
	Status      OInstanceState_Status `protobuf:"varint,3,opt,name=status,proto3,enum=hybsterxpb.OInstanceState_Status" json:"status,omitempty"`
	Instances   []InstanceID          `protobuf:"bytes,4,rep,name=instances,proto3" json:"instances"`
	CommandHash []byte                `protobuf:"bytes,5,opt,name=command_hash,json=commandHash,proto3" json:"command_hash,omitempty"`
}

func (m *OInstanceState) Reset()         { *m = OInstanceState{} }
func (m *OInstanceState) String() string { return proto.CompactTextString(m) }
func (*OInstanceState) ProtoMessage()    {}
func (*OInstanceState) Descriptor() ([]byte, []int) {
	return fileDescriptor_2d276307e2212edc, []int{4}
}
func (m *OInstanceState) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *OInstanceState) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_OInstanceState.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *OInstanceState) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OInstanceState.Merge(m, src)
}
func (m *OInstanceState) XXX_Size() int {
	return m.Size()
}
func (m *OInstanceState) XXX_DiscardUnknown() {
	xxx_messageInfo_OInstanceState.DiscardUnknown(m)
}

var xxx_messageInfo_OInstanceState proto.InternalMessageInfo

func (m *OInstanceState) GetView() View {
	if m != nil {
		return m.View
	}
	return 0
}

func (m *OInstanceState) GetIndex() Index {
	if m != nil {
		return m.Index
	}
	return 0
}

func (m *OInstanceState) GetStatus() OInstanceState_Status {
	if m != nil {
		return m.Status
	}
	return OInstanceState_None
}

func (m *OInstanceState) GetInstances() []InstanceID {
	if m != nil {
		return m.Instances
	}
	return nil
}

func (m *OInstanceState) GetCommandHash() []byte {
	if m != nil {
		return m.CommandHash
	}
	return nil
}

type ONormalMessage struct {
	View        View                `protobuf:"varint,1,opt,name=view,proto3,casttype=View" json:"view,omitempty"`
	Index       Index               `protobuf:"varint,2,opt,name=index,proto3,casttype=Index" json:"index,omitempty"`
	Type        ONormalMessage_Type `protobuf:"varint,3,opt,name=type,proto3,enum=hybsterxpb.ONormalMessage_Type" json:"type,omitempty"`
	Instances   []InstanceID        `protobuf:"bytes,4,rep,name=instances,proto3" json:"instances"`
	CommandHash []byte              `protobuf:"bytes,5,opt,name=command_hash,json=commandHash,proto3" json:"command_hash,omitempty"`
}

func (m *ONormalMessage) Reset()         { *m = ONormalMessage{} }
func (m *ONormalMessage) String() string { return proto.CompactTextString(m) }
func (*ONormalMessage) ProtoMessage()    {}
func (*ONormalMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_2d276307e2212edc, []int{5}
}
func (m *ONormalMessage) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *ONormalMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_ONormalMessage.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *ONormalMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ONormalMessage.Merge(m, src)
}
func (m *ONormalMessage) XXX_Size() int {
	return m.Size()
}
func (m *ONormalMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_ONormalMessage.DiscardUnknown(m)
}

var xxx_messageInfo_ONormalMessage proto.InternalMessageInfo

func (m *ONormalMessage) GetView() View {
	if m != nil {
		return m.View
	}
	return 0
}

func (m *ONormalMessage) GetIndex() Index {
	if m != nil {
		return m.Index
	}
	return 0
}

func (m *ONormalMessage) GetType() ONormalMessage_Type {
	if m != nil {
		return m.Type
	}
	return ONormalMessage_None
}

func (m *ONormalMessage) GetInstances() []InstanceID {
	if m != nil {
		return m.Instances
	}
	return nil
}

func (m *ONormalMessage) GetCommandHash() []byte {
	if m != nil {
		return m.CommandHash
	}
	return nil
}

func init() {
	proto.RegisterEnum("hybsterxpb.InstanceState_Status", InstanceState_Status_name, InstanceState_Status_value)
	proto.RegisterEnum("hybsterxpb.NormalMessage_Type", NormalMessage_Type_name, NormalMessage_Type_value)
	proto.RegisterEnum("hybsterxpb.OInstanceState_Status", OInstanceState_Status_name, OInstanceState_Status_value)
	proto.RegisterEnum("hybsterxpb.ONormalMessage_Type", ONormalMessage_Type_name, ONormalMessage_Type_value)
	proto.RegisterType((*HybsterxMessage)(nil), "hybsterxpb.HybsterxMessage")
	proto.RegisterType((*InstanceID)(nil), "hybsterxpb.InstanceID")
	proto.RegisterType((*InstanceState)(nil), "hybsterxpb.InstanceState")
	proto.RegisterType((*NormalMessage)(nil), "hybsterxpb.NormalMessage")
	proto.RegisterType((*OInstanceState)(nil), "hybsterxpb.OInstanceState")
	proto.RegisterType((*ONormalMessage)(nil), "hybsterxpb.ONormalMessage")
}

func init() {
	proto.RegisterFile("protocols/hybsterx/hybsterxpb/hybsterx.proto", fileDescriptor_2d276307e2212edc)
}

var fileDescriptor_2d276307e2212edc = []byte{
	// 637 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xbc, 0x55, 0xc1, 0x6e, 0xd3, 0x4c,
	0x10, 0x8e, 0x13, 0xd7, 0x49, 0x27, 0x69, 0xff, 0x68, 0xf5, 0x0b, 0x99, 0x0a, 0xd9, 0xa9, 0xb9,
	0x14, 0x51, 0x6c, 0xa9, 0x95, 0x2a, 0x40, 0xe2, 0x40, 0x28, 0x52, 0x2d, 0x44, 0x53, 0xb9, 0x88,
	0x03, 0x08, 0x55, 0x6b, 0x7b, 0xe5, 0x18, 0x1a, 0xaf, 0xe5, 0x75, 0x68, 0xfb, 0x02, 0x9c, 0x38,
	0xf4, 0x31, 0x10, 0xcf, 0xc1, 0xa1, 0xc7, 0x1e, 0x39, 0x59, 0x28, 0x7d, 0x8b, 0x9e, 0x90, 0xd7,
	0xeb, 0x26, 0x2d, 0x34, 0xa5, 0x12, 0xf4, 0x62, 0xcf, 0xce, 0x7c, 0x33, 0x3b, 0xfb, 0xcd, 0xe7,
	0x35, 0x2c, 0xc7, 0x09, 0x4d, 0xa9, 0x47, 0x77, 0x99, 0xd5, 0x3f, 0x70, 0x59, 0x4a, 0x92, 0xfd,
	0x33, 0x23, 0x76, 0xcf, 0x4c, 0x93, 0xc3, 0x10, 0x8c, 0x43, 0x0b, 0xff, 0x07, 0x34, 0xa0, 0xdc,
	0x6d, 0xe5, 0x56, 0x81, 0x58, 0xb8, 0x1b, 0x7f, 0x08, 0x2c, 0x8f, 0x0e, 0x06, 0x38, 0xf2, 0xcb,
	0x77, 0xec, 0x96, 0x56, 0x01, 0x32, 0x3e, 0x49, 0xf0, 0xdf, 0x86, 0xa8, 0xf4, 0x92, 0x30, 0x86,
	0x03, 0x82, 0x56, 0x41, 0x89, 0x68, 0x32, 0xc0, 0xbb, 0xaa, 0xd4, 0x91, 0x96, 0x9a, 0x2b, 0xb7,
	0xcd, 0xf1, 0x5e, 0xe6, 0x26, 0x8f, 0x08, 0xe8, 0x46, 0xc5, 0x11, 0x50, 0xb4, 0x06, 0x75, 0x5a,
	0xc4, 0xd4, 0x2a, 0xcf, 0x5a, 0x98, 0xcc, 0xea, 0x5d, 0x4c, 0x2b, 0xc1, 0x5d, 0x05, 0xe4, 0xf4,
	0x20, 0x26, 0xc6, 0x67, 0x09, 0xc0, 0x8e, 0x58, 0x8a, 0x23, 0x8f, 0xd8, 0xeb, 0xe8, 0x1d, 0xd4,
	0x63, 0x42, 0x92, 0x9d, 0xd0, 0xe7, 0x4d, 0xc8, 0xdd, 0xf5, 0x51, 0xa6, 0x2b, 0x5b, 0x84, 0x24,
	0xf6, 0xfa, 0x69, 0xa6, 0xaf, 0x05, 0x61, 0xda, 0x1f, 0xba, 0xa6, 0x47, 0x07, 0x56, 0xe8, 0xe2,
	0x5d, 0xfc, 0x3e, 0xc4, 0xc9, 0x30, 0xb2, 0x02, 0xfa, 0xc0, 0xa3, 0x11, 0x23, 0x11, 0x1b, 0x32,
	0x2b, 0x2f, 0xc0, 0x1f, 0xb1, 0x6b, 0x16, 0x99, 0x8e, 0x92, 0x2f, 0x6d, 0x1f, 0xe9, 0x30, 0x13,
	0x46, 0x3e, 0xd9, 0xe7, 0xbd, 0xca, 0xdd, 0xd9, 0xd3, 0x4c, 0x9f, 0xb1, 0x73, 0x87, 0x53, 0xf8,
	0x8d, 0x6f, 0x55, 0x98, 0x2b, 0xdb, 0xd9, 0x4e, 0x71, 0x4a, 0xd0, 0x1d, 0x90, 0x3f, 0x86, 0x64,
	0x4f, 0xb4, 0xd3, 0x38, 0xcd, 0x74, 0xf9, 0x75, 0x48, 0xf6, 0x1c, 0xee, 0x45, 0x2f, 0xa0, 0x19,
	0x0a, 0x78, 0xde, 0x73, 0x41, 0xc1, 0xad, 0x49, 0x0a, 0xc6, 0x87, 0xeb, 0xa2, 0xa3, 0x4c, 0xaf,
	0x8c, 0x32, 0x7d, 0xe2, 0xc0, 0x0e, 0x94, 0xe9, 0xb6, 0x8f, 0x1e, 0x82, 0xc2, 0x52, 0x9c, 0x0e,
	0x99, 0x5a, 0xeb, 0x48, 0x4b, 0xf3, 0x2b, 0x9d, 0xdf, 0xd5, 0xe1, 0x5d, 0x99, 0xdb, 0x1c, 0xe7,
	0x08, 0x3c, 0x5a, 0x86, 0xba, 0x98, 0xaf, 0x2a, 0xf3, 0x16, 0x90, 0x79, 0x36, 0x79, 0xf3, 0x59,
	0x61, 0x39, 0x25, 0x04, 0x2d, 0x42, 0x4b, 0x98, 0x3b, 0x7d, 0xcc, 0xfa, 0xea, 0x4c, 0x47, 0x5a,
	0x6a, 0x39, 0x4d, 0xe1, 0xdb, 0xc0, 0xac, 0x6f, 0x3c, 0x01, 0xa5, 0xd8, 0x02, 0x35, 0x40, 0xde,
	0xa4, 0x11, 0x69, 0x57, 0x50, 0x0b, 0x1a, 0x5b, 0x09, 0x89, 0x71, 0x42, 0xfc, 0xb6, 0x84, 0xe6,
	0x60, 0x36, 0x2f, 0x1c, 0xa6, 0x29, 0xf1, 0xdb, 0xd5, 0x3c, 0xf8, 0x7c, 0x9f, 0x78, 0xc3, 0x7c,
	0x55, 0x33, 0xbe, 0x56, 0x61, 0xee, 0xdc, 0xe8, 0x6f, 0x92, 0xc6, 0x95, 0x42, 0x5a, 0x82, 0x44,
	0xed, 0x52, 0x15, 0x9b, 0xaf, 0x0e, 0x62, 0xe2, 0x70, 0xec, 0xdf, 0x27, 0xf0, 0x1e, 0xc8, 0x79,
	0xf9, 0x09, 0xfa, 0x9a, 0x50, 0x17, 0xf4, 0xb5, 0x25, 0x04, 0xa0, 0x14, 0xec, 0xb5, 0x6b, 0xc6,
	0x97, 0x2a, 0xcc, 0xf7, 0xae, 0x23, 0xba, 0xab, 0x54, 0x8c, 0x1e, 0x5d, 0x10, 0xd2, 0xe2, 0xb9,
	0x6f, 0x72, 0xaa, 0x92, 0x1e, 0xc3, 0x6c, 0x49, 0x25, 0x53, 0xe5, 0x4e, 0x6d, 0xca, 0x1c, 0xe4,
	0x7c, 0x0e, 0xce, 0x18, 0x7e, 0x03, 0xba, 0x3a, 0xcc, 0xa9, 0xba, 0x8e, 0xb0, 0xae, 0xa4, 0x6a,
	0xf5, 0x9c, 0x58, 0xf4, 0xcb, 0x2f, 0xaf, 0x49, 0xb5, 0xfc, 0x63, 0x92, 0xee, 0xff, 0xa2, 0x9d,
	0x16, 0x34, 0x7a, 0x63, 0xf1, 0x34, 0xa1, 0xde, 0x13, 0xea, 0xa9, 0x76, 0xdf, 0x1e, 0x8d, 0x34,
	0xe9, 0x78, 0xa4, 0x49, 0x3f, 0x46, 0x9a, 0x74, 0x78, 0xa2, 0x55, 0x8e, 0x4f, 0xb4, 0xca, 0xf7,
	0x13, 0xad, 0xf2, 0xe6, 0xe9, 0x1f, 0x5d, 0x96, 0xd3, 0x7e, 0x3e, 0xae, 0xc2, 0xc3, 0xab, 0x3f,
	0x03, 0x00, 0x00, 0xff, 0xff, 0x83, 0xc2, 0xf5, 0xa8, 0xa4, 0x06, 0x00, 0x00,
}

func (m *HybsterxMessage) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *HybsterxMessage) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *HybsterxMessage) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Type != nil {
		{
			size := m.Type.Size()
			i -= size
			if _, err := m.Type.MarshalTo(dAtA[i:]); err != nil {
				return 0, err
			}
		}
	}
	return len(dAtA) - i, nil
}

func (m *HybsterxMessage_Normal) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *HybsterxMessage_Normal) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	if m.Normal != nil {
		{
			size, err := m.Normal.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintHybsterx(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}
func (m *HybsterxMessage_ONormal) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *HybsterxMessage_ONormal) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	if m.ONormal != nil {
		{
			size, err := m.ONormal.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintHybsterx(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x12
	}
	return len(dAtA) - i, nil
}
func (m *InstanceID) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *InstanceID) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *InstanceID) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Index != 0 {
		i = encodeVarintHybsterx(dAtA, i, uint64(m.Index))
		i--
		dAtA[i] = 0x10
	}
	if m.PeerID != 0 {
		i = encodeVarintHybsterx(dAtA, i, uint64(m.PeerID))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *InstanceState) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *InstanceState) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *InstanceState) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.CommandHash) > 0 {
		i -= len(m.CommandHash)
		copy(dAtA[i:], m.CommandHash)
		i = encodeVarintHybsterx(dAtA, i, uint64(len(m.CommandHash)))
		i--
		dAtA[i] = 0x2a
	}
	if m.Command != nil {
		{
			size, err := m.Command.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintHybsterx(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x22
	}
	if m.Status != 0 {
		i = encodeVarintHybsterx(dAtA, i, uint64(m.Status))
		i--
		dAtA[i] = 0x18
	}
	{
		size, err := m.InstanceID.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintHybsterx(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x12
	if m.View != 0 {
		i = encodeVarintHybsterx(dAtA, i, uint64(m.View))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *NormalMessage) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *NormalMessage) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *NormalMessage) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.CommandHash) > 0 {
		i -= len(m.CommandHash)
		copy(dAtA[i:], m.CommandHash)
		i = encodeVarintHybsterx(dAtA, i, uint64(len(m.CommandHash)))
		i--
		dAtA[i] = 0x2a
	}
	if m.Command != nil {
		{
			size, err := m.Command.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintHybsterx(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x22
	}
	if m.Type != 0 {
		i = encodeVarintHybsterx(dAtA, i, uint64(m.Type))
		i--
		dAtA[i] = 0x18
	}
	{
		size, err := m.InstanceID.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintHybsterx(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x12
	if m.View != 0 {
		i = encodeVarintHybsterx(dAtA, i, uint64(m.View))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *OInstanceState) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *OInstanceState) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *OInstanceState) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.CommandHash) > 0 {
		i -= len(m.CommandHash)
		copy(dAtA[i:], m.CommandHash)
		i = encodeVarintHybsterx(dAtA, i, uint64(len(m.CommandHash)))
		i--
		dAtA[i] = 0x2a
	}
	if len(m.Instances) > 0 {
		for iNdEx := len(m.Instances) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Instances[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintHybsterx(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x22
		}
	}
	if m.Status != 0 {
		i = encodeVarintHybsterx(dAtA, i, uint64(m.Status))
		i--
		dAtA[i] = 0x18
	}
	if m.Index != 0 {
		i = encodeVarintHybsterx(dAtA, i, uint64(m.Index))
		i--
		dAtA[i] = 0x10
	}
	if m.View != 0 {
		i = encodeVarintHybsterx(dAtA, i, uint64(m.View))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *ONormalMessage) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *ONormalMessage) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *ONormalMessage) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.CommandHash) > 0 {
		i -= len(m.CommandHash)
		copy(dAtA[i:], m.CommandHash)
		i = encodeVarintHybsterx(dAtA, i, uint64(len(m.CommandHash)))
		i--
		dAtA[i] = 0x2a
	}
	if len(m.Instances) > 0 {
		for iNdEx := len(m.Instances) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Instances[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintHybsterx(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x22
		}
	}
	if m.Type != 0 {
		i = encodeVarintHybsterx(dAtA, i, uint64(m.Type))
		i--
		dAtA[i] = 0x18
	}
	if m.Index != 0 {
		i = encodeVarintHybsterx(dAtA, i, uint64(m.Index))
		i--
		dAtA[i] = 0x10
	}
	if m.View != 0 {
		i = encodeVarintHybsterx(dAtA, i, uint64(m.View))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func encodeVarintHybsterx(dAtA []byte, offset int, v uint64) int {
	offset -= sovHybsterx(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *HybsterxMessage) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Type != nil {
		n += m.Type.Size()
	}
	return n
}

func (m *HybsterxMessage_Normal) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Normal != nil {
		l = m.Normal.Size()
		n += 1 + l + sovHybsterx(uint64(l))
	}
	return n
}
func (m *HybsterxMessage_ONormal) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.ONormal != nil {
		l = m.ONormal.Size()
		n += 1 + l + sovHybsterx(uint64(l))
	}
	return n
}
func (m *InstanceID) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.PeerID != 0 {
		n += 1 + sovHybsterx(uint64(m.PeerID))
	}
	if m.Index != 0 {
		n += 1 + sovHybsterx(uint64(m.Index))
	}
	return n
}

func (m *InstanceState) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.View != 0 {
		n += 1 + sovHybsterx(uint64(m.View))
	}
	l = m.InstanceID.Size()
	n += 1 + l + sovHybsterx(uint64(l))
	if m.Status != 0 {
		n += 1 + sovHybsterx(uint64(m.Status))
	}
	if m.Command != nil {
		l = m.Command.Size()
		n += 1 + l + sovHybsterx(uint64(l))
	}
	l = len(m.CommandHash)
	if l > 0 {
		n += 1 + l + sovHybsterx(uint64(l))
	}
	return n
}

func (m *NormalMessage) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.View != 0 {
		n += 1 + sovHybsterx(uint64(m.View))
	}
	l = m.InstanceID.Size()
	n += 1 + l + sovHybsterx(uint64(l))
	if m.Type != 0 {
		n += 1 + sovHybsterx(uint64(m.Type))
	}
	if m.Command != nil {
		l = m.Command.Size()
		n += 1 + l + sovHybsterx(uint64(l))
	}
	l = len(m.CommandHash)
	if l > 0 {
		n += 1 + l + sovHybsterx(uint64(l))
	}
	return n
}

func (m *OInstanceState) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.View != 0 {
		n += 1 + sovHybsterx(uint64(m.View))
	}
	if m.Index != 0 {
		n += 1 + sovHybsterx(uint64(m.Index))
	}
	if m.Status != 0 {
		n += 1 + sovHybsterx(uint64(m.Status))
	}
	if len(m.Instances) > 0 {
		for _, e := range m.Instances {
			l = e.Size()
			n += 1 + l + sovHybsterx(uint64(l))
		}
	}
	l = len(m.CommandHash)
	if l > 0 {
		n += 1 + l + sovHybsterx(uint64(l))
	}
	return n
}

func (m *ONormalMessage) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.View != 0 {
		n += 1 + sovHybsterx(uint64(m.View))
	}
	if m.Index != 0 {
		n += 1 + sovHybsterx(uint64(m.Index))
	}
	if m.Type != 0 {
		n += 1 + sovHybsterx(uint64(m.Type))
	}
	if len(m.Instances) > 0 {
		for _, e := range m.Instances {
			l = e.Size()
			n += 1 + l + sovHybsterx(uint64(l))
		}
	}
	l = len(m.CommandHash)
	if l > 0 {
		n += 1 + l + sovHybsterx(uint64(l))
	}
	return n
}

func sovHybsterx(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozHybsterx(x uint64) (n int) {
	return sovHybsterx(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *HybsterxMessage) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowHybsterx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: HybsterxMessage: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: HybsterxMessage: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Normal", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowHybsterx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthHybsterx
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthHybsterx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			v := &NormalMessage{}
			if err := v.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			m.Type = &HybsterxMessage_Normal{v}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ONormal", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowHybsterx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthHybsterx
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthHybsterx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			v := &ONormalMessage{}
			if err := v.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			m.Type = &HybsterxMessage_ONormal{v}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipHybsterx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthHybsterx
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthHybsterx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *InstanceID) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowHybsterx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: InstanceID: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: InstanceID: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field PeerID", wireType)
			}
			m.PeerID = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowHybsterx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.PeerID |= github_com_ibalajiarun_go_consensus_peer_peerpb.PeerID(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Index", wireType)
			}
			m.Index = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowHybsterx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Index |= Index(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipHybsterx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthHybsterx
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthHybsterx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *InstanceState) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowHybsterx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: InstanceState: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: InstanceState: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field View", wireType)
			}
			m.View = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowHybsterx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.View |= View(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field InstanceID", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowHybsterx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthHybsterx
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthHybsterx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.InstanceID.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Status", wireType)
			}
			m.Status = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowHybsterx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Status |= InstanceState_Status(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Command", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowHybsterx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthHybsterx
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthHybsterx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Command == nil {
				m.Command = &commandpb.Command{}
			}
			if err := m.Command.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field CommandHash", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowHybsterx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthHybsterx
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthHybsterx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.CommandHash = append(m.CommandHash[:0], dAtA[iNdEx:postIndex]...)
			if m.CommandHash == nil {
				m.CommandHash = []byte{}
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipHybsterx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthHybsterx
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthHybsterx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *NormalMessage) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowHybsterx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: NormalMessage: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: NormalMessage: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field View", wireType)
			}
			m.View = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowHybsterx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.View |= View(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field InstanceID", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowHybsterx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthHybsterx
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthHybsterx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.InstanceID.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Type", wireType)
			}
			m.Type = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowHybsterx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Type |= NormalMessage_Type(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Command", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowHybsterx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthHybsterx
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthHybsterx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Command == nil {
				m.Command = &commandpb.Command{}
			}
			if err := m.Command.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field CommandHash", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowHybsterx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthHybsterx
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthHybsterx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.CommandHash = append(m.CommandHash[:0], dAtA[iNdEx:postIndex]...)
			if m.CommandHash == nil {
				m.CommandHash = []byte{}
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipHybsterx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthHybsterx
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthHybsterx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *OInstanceState) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowHybsterx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: OInstanceState: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: OInstanceState: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field View", wireType)
			}
			m.View = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowHybsterx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.View |= View(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Index", wireType)
			}
			m.Index = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowHybsterx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Index |= Index(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Status", wireType)
			}
			m.Status = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowHybsterx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Status |= OInstanceState_Status(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Instances", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowHybsterx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthHybsterx
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthHybsterx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Instances = append(m.Instances, InstanceID{})
			if err := m.Instances[len(m.Instances)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field CommandHash", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowHybsterx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthHybsterx
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthHybsterx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.CommandHash = append(m.CommandHash[:0], dAtA[iNdEx:postIndex]...)
			if m.CommandHash == nil {
				m.CommandHash = []byte{}
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipHybsterx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthHybsterx
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthHybsterx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *ONormalMessage) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowHybsterx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: ONormalMessage: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: ONormalMessage: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field View", wireType)
			}
			m.View = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowHybsterx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.View |= View(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Index", wireType)
			}
			m.Index = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowHybsterx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Index |= Index(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Type", wireType)
			}
			m.Type = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowHybsterx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Type |= ONormalMessage_Type(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Instances", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowHybsterx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthHybsterx
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthHybsterx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Instances = append(m.Instances, InstanceID{})
			if err := m.Instances[len(m.Instances)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field CommandHash", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowHybsterx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthHybsterx
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthHybsterx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.CommandHash = append(m.CommandHash[:0], dAtA[iNdEx:postIndex]...)
			if m.CommandHash == nil {
				m.CommandHash = []byte{}
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipHybsterx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthHybsterx
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthHybsterx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipHybsterx(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowHybsterx
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowHybsterx
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowHybsterx
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthHybsterx
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupHybsterx
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthHybsterx
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthHybsterx        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowHybsterx          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupHybsterx = fmt.Errorf("proto: unexpected end of group")
)
