apiVersion: v1
data:
  cloud-config: ewogICAgImNsb3VkIjoiQXp1cmVQdWJsaWNDbG91ZCIsCiAgICAidGVuYW50SWQiOiAiNjA5NTY4ODQtMTBhZC00MGZhLTg2M2QtNGYzMmMxZTNhMzdhIiwKICAgICJzdWJzY3JpcHRpb25JZCI6ICI4NTBkMTViNy05ZDBmLTRlMTktYjRkYi0zZjkyYjhiMmE5YjAiLAogICAgImFhZENsaWVudElkIjogImZjOWM0MzA1LTg1M2ItNDQ3OS05YTEzLTI5MDcwNmI4MTBkMSIsCiAgICAiYWFkQ2xpZW50U2VjcmV0IjogImh5bmZMR0dyMDVVZndxblotZXpfdX5GWG9FOXV6OGtlWi0iLAogICAgInJlc291cmNlR3JvdXAiOiAiZGVzdGlueS1yZyIsCiAgICAibG9jYXRpb24iOiAiZWFzdHVzIiwKICAgICJ2bVR5cGUiOiAic3RhbmRhcmQiLAogICAgInVzZUluc3RhbmNlTWV0YWRhdGEiOiB0cnVlCn0=
kind: Secret
metadata:
  name: azure-cloud-provider
  namespace: kube-system
type: Opaque